import type { Metadata } from 'next'
import AppShell from '@/components/layout/AppShell'
import Link from 'next/link'
import { ChevronRight, Shield } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for DevCipher — all tool processing is local in your browser. No data is collected or transmitted.',
}

export default function PrivacyPage() {
  return (
    <AppShell>
      <nav className="flex items-center gap-1 text-xs text-zinc-500 mb-8">
        <Link href="/" className="hover:text-zinc-300 transition-colors">Home</Link>
        <ChevronRight className="h-3 w-3" />
        <span className="text-zinc-200">Privacy Policy</span>
      </nav>

      <div className="max-w-2xl mx-auto space-y-8">
        <div>
          <div className="flex items-center gap-3 mb-3">
            <Shield className="h-6 w-6 text-emerald-400" />
            <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
          </div>
          <p className="text-zinc-500 text-sm">Last updated: April 2026</p>
        </div>

        {/* TL;DR */}
        <div className="rounded-xl border border-emerald-800/40 bg-emerald-900/10 p-5">
          <p className="text-sm font-semibold text-emerald-300 mb-2">The short version</p>
          <p className="text-zinc-400 text-sm leading-relaxed">
            DevCipher does not collect, store, transmit, or share any data you enter into the tools.
            All cryptographic operations happen entirely inside your browser. There is no analytics,
            no tracking pixels, no cookies from us, and no account system.
          </p>
        </div>

        {[
          {
            title: '1. Who We Are',
            body: `DevCipher (devcipher.dev) is a free, open-source developer tool site created and
            maintained by Animesh Shaw. It is a personal project, not a commercial entity.
            Contact: animeshshaw@pm.me`,
          },
          {
            title: '2. Data We Do Not Collect',
            items: [
              'Any text, keys, or data you enter into any tool',
              'Hashes, ciphertext, or any output generated by the tools',
              'Your IP address (no server logs — the site is static)',
              'Browser fingerprints or device identifiers',
              'Names, email addresses, or any personal information',
            ],
          },
          {
            title: '3. How the Tools Work',
            body: `Every tool on DevCipher runs as JavaScript inside your browser. When you enter
            text and click a button, the computation happens locally on your device. No input or
            output is sent over the network to any server — not ours, not third-party. You can
            verify this by inspecting the network tab in your browser's developer tools.`,
          },
          {
            title: '4. Hosting Infrastructure',
            body: `DevCipher is hosted as a static site on GitHub Pages. GitHub may log standard
            HTTP access logs (IP address, User-Agent, timestamp) as part of their infrastructure.
            This is governed by GitHub's own Privacy Policy. We do not have access to or control
            over those logs.`,
          },
          {
            title: '5. Cookies',
            body: `DevCipher does not set any cookies. No session cookies, no preference cookies,
            no tracking cookies. See our Cookie Policy for more details.`,
          },
          {
            title: '6. Third-Party Services',
            body: `DevCipher does not integrate with any third-party analytics, advertising, or
            tracking services (no Google Analytics, no Mixpanel, no Facebook Pixel, etc.).
            The only external links are to GitHub, LinkedIn, Ko-fi, and GitHub Sponsors — clicking
            these takes you to third-party sites governed by their own privacy policies.`,
          },
          {
            title: '7. Open Source Verification',
            body: `Because DevCipher is open source and statically exported, you can inspect every
            line of JavaScript running in your browser. The source is on GitHub and every build
            is attested with Sigstore, linking the deployed artifact to the exact commit it was
            built from.`,
          },
          {
            title: '8. Children\'s Privacy',
            body: `DevCipher is not directed at children under 13. We do not knowingly collect any
            information from children. As no data is collected from any user, there is no special
            risk to children.`,
          },
          {
            title: '9. Changes to This Policy',
            body: `This policy may be updated periodically. The "Last updated" date above will
            reflect any changes. Continued use of DevCipher constitutes acceptance of the
            updated policy.`,
          },
          {
            title: '10. Contact',
            contact: true,
          },
        ].map(({ title, body, items, contact }: { title: string; body?: string; items?: string[]; contact?: boolean }) => (
          <div key={title} className="space-y-2">
            <h2 className="text-base font-semibold text-zinc-200">{title}</h2>
            {body && <p className="text-zinc-400 leading-relaxed text-sm">{body}</p>}
            {items && (
              <ul className="space-y-1.5 pl-1">
                {items.map((item) => (
                  <li key={item} className="flex items-start gap-2 text-sm text-zinc-400">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            )}
            {contact && (
              <p className="text-zinc-400 leading-relaxed text-sm">
                For any privacy-related questions, contact{' '}
                <a href="mailto:animeshshaw@pm.me" className="text-indigo-400 hover:text-indigo-300">
                  animeshshaw@pm.me
                </a>{' '}
                or visit the{' '}
                <Link href="/contact" className="text-indigo-400 hover:text-indigo-300">
                  Contact page
                </Link>.
              </p>
            )}
          </div>
        ))}
      </div>
    </AppShell>
  )
}
